In [ ]:
!wget "https://www.dropbox.com/s/c6lmwqz67kpdsiq/review_dataset.csv"

--2020-10-21 17:39:40--  https://www.dropbox.com/s/c6lmwqz67kpdsiq/review_dataset.csv
Resolving www.dropbox.com (www.dropbox.com)... 162.125.9.1, 2620:100:601f:1::a27d:901
Connecting to www.dropbox.com (www.dropbox.com)|162.125.9.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/c6lmwqz67kpdsiq/review_dataset.csv [following]
--2020-10-21 17:39:40--  https://www.dropbox.com/s/raw/c6lmwqz67kpdsiq/review_dataset.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc69cb4d85a7e1421d83694c11b0.dl.dropboxusercontent.com/cd/0/inline/BBtpkheb-0yg4jVnIy-e7V0HTTrDyCBOWLS5UYiYu6yfSqYE7QCy3XHqwUkPdK3ckbKZKNqh4XE-pty5SoHL8xS0AZRA9yzI7eKUPODGFYva4G3UDGWV_hSRQphFZyM007o/file# [following]
--2020-10-21 17:39:40--  https://uc69cb4d85a7e1421d83694c11b0.dl.dropboxusercontent.com/cd/0/inline/BBtpkheb-0yg4jVnIy-e7V0HTTrDyCBOWLS5UYiYu6yfSqYE7QCy3XHqwUkPdK3ckbKZKNqh4XE-pty5SoHL8xS0AZRA9yzI

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("review_dataset.csv")

In [ ]:
df.shape

(20000, 2)

In [ ]:
df['label']

0        pos
1        neg
2        neg
3        pos
4        neg
        ... 
19995    neg
19996    pos
19997    neg
19998    neg
19999    pos
Name: label, Length: 20000, dtype: object

In [ ]:
df['review']

0        The Buddy Holly Story opens on a shot of a yel...
1        ***SPOILERS*** Like some evil Tinkers-to-Evers...
2        Ghost of Dragstrip Hollow is a typical 1950's ...
3        Whatever you do, don't stop watching when you ...
4        This is one of those movies you think that the...
                               ...                        
19995    O boy, was this really bad.<br /><br />I saw t...
19996    Larry Fessenden has been thrashed by most of t...
19997    This may or may not be the worst movie that St...
19998    I have no idea what these people were thinking...
19999    "The Groove Tube" was initially shown on video...
Name: review, Length: 20000, dtype: object

In [ ]:
df['review'][1]

'***SPOILERS*** Like some evil Tinkers-to-Evers-to-Chance double-play combination we have in "Omen IV" the evil seed of the deceased AntiChrist Damien Thorn come back. Terrorizing his parents his schoolmates his neighbors and finally the entire world as a she named Delia York, Asia Vieila. After being given to a "deserving" couple the Yorks Karen & Gene, Fay Grant & Michael Woods,by the Catholic Church\'s St. Francis orphanage.<br /><br />Little Delia didn\'t waste any time making her peasants felt by scratching her mom at a house party. Later Delia almost get killed by a runaway truck only to have herself saved by this "Devil Dog" named Ryder. Going to school Delia takes care of the local bully by getting the big guy to wet himself in front of all his classmates. Later when his father threatens the Yorks with a law suit she has his head sliced off in a self-induced traffic accident! Delia is someone that you never mess with if you know what\'s good for you.<br /><br />Meanwhile Dalia\

In [ ]:
import re
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
sw= stopwords.words('english')
sw

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
def clean_text(sample):
  sample = sample.lower()
  sample= sample.replace("<br /><br />","")
  sample=re.sub("[^a-z]+"," ",sample)
  sample=sample.split()
  sample=[word for word in sample if word not in sw]
  sample=" ".join(sample)
  return sample

In [ ]:
clean_text(df['review'][1])

'spoilers like evil tinkers evers chance double play combination omen iv evil seed deceased antichrist damien thorn come back terrorizing parents schoolmates neighbors finally entire world named delia york asia vieila given deserving couple yorks karen gene fay grant michael woods catholic church st francis orphanage little delia waste time making peasants felt scratching mom house party later delia almost get killed runaway truck saved devil dog named ryder going school delia takes care local bully getting big guy wet front classmates later father threatens yorks law suit head sliced self induced traffic accident delia someone never mess know good meanwhile dalia dad gene becomes big man town thinks getting elected congress champion clean air green trees crowd instead letting smog concrete boys take neighborhood eye white house bratty strange daughter delia anything gene york sudden good fortune later jo ann hearen hired delia nanny truth comes strange evil powers jo new age type real

In [ ]:
df['review']=df['review'].apply(clean_text)

In [ ]:
df['review']

0        buddy holly story opens shot yellow neon moon ...
1        spoilers like evil tinkers evers chance double...
2        ghost dragstrip hollow typical teens turmoil m...
3        whatever stop watching think movie hang around...
4        one movies think makers would refuse release t...
                               ...                        
19995    boy really bad saw videotape scenes soundtrack...
19996    larry fessenden thrashed comments forum well w...
19997    may may worst movie steve martin ever made cer...
19998    idea people thinking made film plot limited ac...
19999    groove tube initially shown video first video ...
Name: review, Length: 20000, dtype: object

In [ ]:
x=df['review'].values
y=df['label'].values

In [ ]:
x_train=x[0:15000]
x_test=x[15000:20000]
y_train=y[0:15000]
y_test=y[15000:20000]

In [ ]:
y_train

array(['pos', 'neg', 'neg', ..., 'pos', 'pos', 'pos'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [ ]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [ ]:
y_train[0:20]

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0])

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(max_features=10000)

In [ ]:
cv.fit(x_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=10000, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [ ]:
x_train=cv.transform(x_train).toarray()

In [ ]:
x_train.shape

(15000, 10000)

In [ ]:
x_test=cv.transform(x_test).toarray()

In [ ]:
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB()

In [ ]:
mnb.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
mnb.predict(x_test)

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
mnb.score(x_test,y_test)

0.8416

In [ ]:
my_review="The characters that inhabit a Nancy Meyers (Something’s Gotta Give, The Holiday, What Women Want etc) film are usually fairly well-off and seemingly, don’t have much to worry about except for maybe, their love lives. For Meyers, it’s the kind of tried-and-tested confection that plays it safe and sweet.Therefore, if not for De Niro’s presence here, this movie would have been just another by-the-numbers flick about millennials and their various issues. Sure, Anne Hathaway does essay her somewhat conflicted character as the fast-paced (she rides a cycle in the office and personally takes random customer calls) startup owner who juggles a family life too, quite well but it is not something that any other actress in her league could not have done equally well, if not better."

In [ ]:
my_review=clean_text(my_review)

In [ ]:
my_review=cv.transform([my_review])

In [ ]:
mnb.predict(my_review)

array([1])